[2025-06-08 13:35:53,040 INFO] Parsed arguments: {'model': 'meta-llama/Llama-3.2-1B', 'tasks': ['arc_easy'], 'num_fewshot': 0, 'seed': 42, 'limit': None, 'batch_size': 4, 'output_dir': 'results/meta-llama/Llama-3.2-1B_arc_easy_english', 'cache_opt': False, 'double_buffer': False, 'temperature': 0.7, 'engine': 'hf', 'language': 'english'}
[2025-06-08 13:35:56,006 INFO] Based on the current allocation process, no modules could be assigned to the following devices due to insufficient memory:
  - 0: 1293959168 bytes required
These minimum requirements are specific to this allocation attempt and may vary. Consider increasing the available memory for these devices to at least the specified minimum, or adjusting the model config.
[2025-06-08 13:37:18,842 INFO] Evaluating arc_easy...
[2025-06-08 13:37:18,844 ERROR] Exception during evaluate():
[2025-06-08 13:37:18,844 ERROR] Traceback (most recent call last):
  File "/home/s1/jypark/twice/main.py", line 125, in main
    df =evaluate(args, tasks,args.language)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s1/jypark/twice/cli_evaluator.py", line 79, in evaluate
    dataset, answer, og_dataset = load(name=task,
                                 ^^^^^^^^^^^^^^^
  File "/home/s1/jypark/twice/loader/load.py", line 34, in load
    raise RuntimeError("OPENAI_API_KEY environment variable not set")
RuntimeError: OPENAI_API_KEY environment variable not set

